name: fedora/39

on:
  push:
    branches:
      - '**'
    paths:
      - fedora/39/**
  pull_request:
    paths:
      - fedora/39/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  image:
    # A pull request from a branch of this repository is skipped: the push
    # to that branch builds the same changes.
    if: >-
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/image.yml
    with:
      dir: fedora/39
      tag: fedora-39
    secrets: inherit
